### ISSUE TITLE
Follow manga and mark chapters as read

### ISSUE THREAD

**Issue by samir-araujo** [md-y/mangadex-full-api#30]
Hi!

Thanks for the nice API.
But I have been wondering, is it possibile to follow a manga and mark chapters as read?
I'm thinking about building a migration tool from Tachiyomi to Manga Dex.

Sorry if this is not the right channel to ask

**Comment by md-y** [comment]
Mangadex doesn't handle marking chapters as read very well, even on the website. The official documentation claims that chapters will be marked read when called through the API by default, but this does not happen. Even when the parameter is specifically added, it refuses both through Nodejs and a normal web browser.

The website uses AJAX to mark chapters as read, but naively using the same method with a GET request causes Mangadex to refuse it. In addition, simply marking the chapter as read/unread on the website only works half of the time, so I am assuming the issue is on Mangadex's side. 

There may be a way to force it to work, but I do not have the time to try it, and this is also an issue thread. If you wish to attempt it yourself, I would advise looking at [Mangadex's documentation](http://api.mangadex.org/v2/) and ```Util.getHTTPS()``` since this function always uses authentication. If you do succeed, please submit a pull request rather than an issue.
