### ISSUE TITLE
manga.lastChapter is returning different value from manga.getFeed()

### ISSUE THREAD

**Issue by johnlim5847** [md-y/mangadex-full-api#36]
Hi all, I noticed the value for `manga.lastChapter` is different from `manga.getFeed()`

```JS
const manga = await MFA.Manga.get('32d76d19-8a05-4db0-9fc2-e0b0648fe9d0');
manga.lastChapter // 108

const feeds = await manga.getFeed({
        limit: Infinity,
        translatedLanguage: ["en"],
        "order[chapter]": "desc",
      });

feeds[0].chapter // 144
```

Not sure this is a bug, or I understand the feed chapter id wrongly

**Comment by Curstantine** [comment]
`.lastChapter` returns a string because it's not a function, it only gives you the `lastChapter` field returned by the response.  
`getFeed()` is a function that returns chapter data from the `/manga/id/feed`.

![image](https://user-images.githubusercontent.com/69104500/120921888-b3b82e00-c6e3-11eb-95aa-232f32bcfb0e.png)
![image](https://user-images.githubusercontent.com/69104500/120921911-d34f5680-c6e3-11eb-913a-f4661f2fcbd2.png)

https://api.mangadex.org/docs.html#operation/get-manga-id
https://github.com/md-y/mangadex-full-api/blob/934d7e0ef342d8a87171a4aaf69067076af45046/src/structure/manga.js#L85
https://github.com/md-y/mangadex-full-api/blob/934d7e0ef342d8a87171a4aaf69067076af45046/src/structure/manga.js#L393

**Comment by md-y** [comment]
```lastChapter``` and ```lastVolume``` are both returned as attributes of manga objects returned by Mangadex, so they are included as a part of the Manga class. Their values seem to be dependent on the default feed order because [the first chapter based on default order](https://api.mangadex.org/manga/32d76d19-8a05-4db0-9fc2-e0b0648fe9d0/feed?limit=1) seems to be the same as the [Manga attribute](https://api.mangadex.org/manga/32d76d19-8a05-4db0-9fc2-e0b0648fe9d0).

However, this seems incorrect as @johnlim5847 described ([this chapter](https://api.mangadex.org/manga/32d76d19-8a05-4db0-9fc2-e0b0648fe9d0/feed?order[chapter]=desc&limit=1&translatedLanguage[]=en) is ahead by 40+ chapters). Therefore, this may be a bug on Mangadex's end or I am misunderstanding it, so for now only use ```lastChapter```/```lastVolume``` as representations of the chapter number and volume number of the first chapter in the default feed. For any other context, using a feed request with a limit of one to get the most recent/highest-number chapter in a certain language seems like the best option.

On another note, during previous versions of the official MD API, ```lastChapter``` contained non-number titles, but while researching this issue, it seems that all occurrences of this attribute have become numbers like ```lastVolume```, so the type of ```Manga.lastChapter``` may become a number like ```Chapter.chapter``` in the next version.

**Comment by johnlim5847** [comment]
@md-y  is there a way to get the feed without getting the rate limit? and is it possible to open up the discussion feature for this repo 😁

**Comment by md-y** [comment]
I enabled the discussion feature (TBH I didn't know it existed). 

As for bypassing the rate limit when requesting feeds, assuming you want to get the feeds of multiple different manga, I would create a custom list with the manga you wish to query and get the feed of that custom list. If you still simply wish to get the most recent chapter, however, I coincidentally found a new solution when implementing ```getAggregate```—the function includes a list of volumes and chapter numbers that can be parsed to find the most recent chapter for different languages.

**Comment by johnlim5847** [comment]
@md-y thank you! I will wait for the `getAggregate` function :), personally find it very inefficient to pull the feeds just to get the latest chapter
