### ISSUE TITLE
Wrong result return by fillByQuery

### ISSUE THREAD

**Issue by aahmyu** [md-y/mangadex-full-api#4]
Because fillByQuery is returing the details of the first item, sometimes it is returning the wrong manga, for example searching for 'berserk' will give wrong result.

**Comment by md-y** [comment]
The ```fillByQuery``` function is meant to retrieve manga with unique titles like "3-gatsu no lion" or "Komi-san wa Komyushou Desu" since they only return one result. A side effect of this is the issue you mentioned.

However, I would recommend resolving the problem by using the regular ```search``` function, or wait for [this page](https://mangadex.org/search) to be implemented into the API (probably by the end of the week).
