### ISSUE TITLE
npm run gen-types generates files differently from what is in VCS

### ISSUE THREAD

**Issue by MxBlu** [md-y/mangadex-full-api#40]
What's checked in to git is a single index.d.ts, but running gen-types gets me a .d.ts file for every time in src.

The repo should either swap to the one-per-source-file approach or modify the tsconfig to generate to only generate index.d.ts

**Comment by md-y** [comment]
I had been manually copying and pasting the multiple files into one since having the declarations of classes in one file seems to be better understood by VS Intellisense and other type parsing implementations, but for v5.2.0 I wrote a simple script that combines all of these files into one and included it in ```package.json```.

It isn't pretty, but it works.
