### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ShinNouzen** [md-y/mangadex-full-api#49]
Can you please make the chapters in order?

**Comment by md-y** [comment]
You can dictate the order of chapters for certain endpoints using the ```order``` parameter.
```javascript
const testManga = await MFA.Manga.get('f9c33607-9180-4ba6-b85c-e4b5faee7192');
await testManga.getFeed({ order: { chapter: 'asc' }});
await testManga.getFeed({ order: { chapter: 'desc' }});
await testManga.getFeed({ order: { updatedAt: 'desc' }});
// ...etc
```

Otherwise you can use the sort method on the result array.
```javascript
const testManga = await MFA.Manga.get('f9c33607-9180-4ba6-b85c-e4b5faee7192');
const defaultChapters = await testManga.getFeed();
const sortedChapters = defaultChapters.sort((a, b) => {
    return a.chapter - b.chapter; // or any other sort method
});
```

If this does not answer your question please provide more context than "Request" and "Can you please make the chapters in order?". I will be closing this issue for now.
